### ISSUE TITLE
Revising Documentation

### ISSUE THREAD

**Issue by emstruong** [FloSchuberth/cSEM#497]
This is a general thread for any proposed revisions to the documentation, mainly focusing on clarity and superficial details.

**Comment by emstruong** [comment]
Minor revisions can be made to [CONTRIBUTING.md](https://github.com/M-E-Rademaker/cSEM/blob/c8153a9e15ff1536ce765f499e2197d023a22221/CONTRIBUTING.md) and [CONTRIBUTING.Rmd](https://github.com/M-E-Rademaker/cSEM/blob/c8153a9e15ff1536ce765f499e2197d023a22221/CONTRIBUTING.Rmd) 

- `.appraoch_*` to `.approach_*`
- "Avoid to mix synonyms" to "Avoid mixing synonyms"
- "...instead of where the function starts if this helps with clarity." to "...instead of where the function starts if this helps with readability."

**Comment by emstruong** [comment]
The [API.png](https://github.com/M-E-Rademaker/cSEM/blob/e7a74eefb5901165a7437741cffe90cec4a59f74/man/figures/api.png) is not very readable in GitHub dark mode. I tried applying some fixes in [this new branch](https://github.com/M-E-Rademaker/cSEM/tree/ReviseREADME), but it doesn't work because of [this](https://github.com/orgs/community/discussions/41899) and [this](https://github.com/orgs/community/discussions/39865). 

This could probably be fixed by making a dark-mode specific version of [API.png](https://github.com/M-E-Rademaker/cSEM/blob/e7a74eefb5901165a7437741cffe90cec4a59f74/man/figures/api.png)

**Comment by FloSchuberth** [comment]
@emstruong: I think I could solve the issue, see: https://github.com/FloSchuberth/cSEM
If you agree can you please close this issue.
