### ISSUE TITLE
Missing GPL License File(s)

### ISSUE THREAD

**Issue by emstruong** [FloSchuberth/cSEM#501]
[The CRAN Description File](https://github.com/M-E-Rademaker/cSEM/blob/0110c59e817774b43ec3877505244a1744338f07/DESCRIPTION) mentions GPL-3, but the [LICENSE.md file is missing](https://r-pkgs.org/license.html#key-files).

We might also need [a LICENSE.note file](https://r-pkgs.org/license.html#sec-how-to-include), if any code from other packages/Stack-Overflow is used

**Comment by FloSchuberth** [comment]
This is interesting. I  wasn't aware that such a file should be used. I checked lavaan and it seems they also do not provide a LICENSE.ml file: 
https://github.com/yrosseel/lavaan

Could you create such a file?

**Comment by M-E-Rademaker** [comment]
This seems to be a rather new requirement. I remember back when I started the package, there was no need to add a license file for any of the standard licenses. Note that although the licence states that you should add a file now, CRAN still doesn’t like that. So make sure to add it to .rbuildignore

Taken from: https://r-pkgs.org/license.html

LICENSE.md includes a copy of the full text of the license. All open source licenses require a copy of the license to be included, but CRAN does not permit you to include a copy of standard licenses in your package, so we also use .Rbuildignore to make sure this file is not sent to CRAN.

**Comment by emstruong** [comment]
@FloSchuberth I'll get to this soon! :smile:

**Comment by FloSchuberth** [comment]
@emstruong:Thank for creating the license file and adding it rbuildignore. In this way it should be fine.
