### ISSUE TITLE
.r in predict() doesn't work

### ISSUE THREAD

**Issue by huizhao0804z** [FloSchuberth/cSEM#504]
Hi, 
I met a problem when I conducted predict() function. I tried to set replications, but it seems doesn't work no matter how I change .r

set.seed(123)
index <- sample.int(dim(dataset)[1], 500, replace = FALSE)
dat_test <- dataset[index, ]

test <- cSEM:: predict(
.object = res_VBN_engage,
.r= 5,
.handle_inadmissibles = "ignore",
.test_data = dat_test,
.benchmark = "PLS-PM",
.treat_as_continuous = FALSE
)

________________________________________________________________________________
----------------------------------- Overview -----------------------------------

	Number of obs. training          = 1000
	Number of obs. test                = 500
	Number of cv folds                 = NA
	Number of repetitions              = 1
	Handle inadmissibles               = ignore
	Estimator target                       = 'OrdPLS'
	Estimator benchmark              = 'OrdPLS'
	Disattenuation target              = 'TRUE'
	Disattenuation benchmark           = 'TRUE'
	Approach to predict                = 'earliest'

I'm using the cSEM(0.5.0)

Thanks in advance.

**Comment by emstruong** [comment]
Hi Hui,

Could you please post a [reprex](https://reprex.tidyverse.org/index.html) so that I can reproduce things on my end?

**Comment by huizhao0804z** [comment]
``` r
test <- cSEM:: predict(
.object = res_VBN_engage_test,
.r= 5,
.handle_inadmissibles = "ignore",
.test_data = dat_test,
.benchmark = "PLS-PM",
.treat_as_continuous = FALSE
)
#> Error in cSEM::predict(.object = res_VBN_engage_test, .r = 5, .handle_inadmissibles = "ignore", : object 'res_VBN_engage_test' not found
```

<sup>Created on 2023-07-30 with [reprex v2.0.2](https://reprex.tidyverse.org)</sup>

**Comment by huizhao0804z** [comment]
I attach some information about the pls-sem model for reference:

________________________________________________________________________________
----------------------------------- Overview -----------------------------------

	General information:
	------------------------
	Estimation status                  = Ok
	Number of observations             = 1000
	Weight estimator                   = PLS-PM (OrdPLS)
	Inner weighting scheme             = "path"
	Type of indicator correlation      = polychoric, polyserial, Pearson
	Path model estimator               = OLS
	Second-order approach              = NA
	Type of path model                 = Linear
	Disattenuated                      = Yes (PLSc)

	Resample information:
	---------------------
	Resample method                    = "bootstrap"
	Number of resamples                = 5
	Number of admissible results       = 5
	Approach to handle inadmissibles   = "drop"
	Sign change option                 = "none"
	Random seed                        = 1872981944

**Comment by emstruong** [comment]
> ```r
> test <- cSEM:: predict(
> .object = res_VBN_engage_test,
> .r= 5,
> .handle_inadmissibles = "ignore",
> .test_data = dat_test,
> .benchmark = "PLS-PM",
> .treat_as_continuous = FALSE
> )
> #> Error in cSEM::predict(.object = res_VBN_engage_test, .r = 5, .handle_inadmissibles = "ignore", : object 'res_VBN_engage_test' not found
> ```
> 
> Created on 2023-07-30 with [reprex v2.0.2](https://reprex.tidyverse.org)

Just to be sure, have you first tried running something along the lines of 

```r
res_VBN_engage_test <- cSEM::csem(...)
```

Could you add the fake data you generated and an example model as part of your reprex?

**Comment by huizhao0804z** [comment]
[cSEM_predict.md](https://github.com/FloSchuberth/cSEM/files/12211200/cSEM_predict.md)

I have a problem loading data in reprex(). So I attach the code in .md, in which I use the example data PoliticalDemocracy in lavaan as an example.

**Comment by emstruong** [comment]
I've replicated your issue using your code... it'll take some time to figure out exactly why this happens

``` r
library(lavaan)
#> This is lavaan 0.6-15
#> lavaan is FREE software! Please report any bugs.
library(cSEM)
#> 
#> Attaching package: 'cSEM'
#> The following object is masked from 'package:lavaan':
#> 
#>     predict
#> The following object is masked from 'package:stats':
#> 
#>     predict

# Look at the dataset

PoliticalDemocracy <- lavaan::PoliticalDemocracy

PoliticalDemocracy$y1 <- ordered(PoliticalDemocracy$y1)
PoliticalDemocracy$x1 <- ordered(PoliticalDemocracy$x1)

myModel <- '
   # latent variables
     ind60 =~ x1 + x2 + x3
     dem60 =~ y1 + y2 + y3 + y4
     dem65 =~ y5 + y6 + y7 + y8
   # regressions
     dem60 ~ ind60
     dem65 ~ ind60 + dem60
'
fit <- csem(.model = myModel,
            .data  = PoliticalDemocracy)
cSEM::summarize(fit)
#> ________________________________________________________________________________
#> ----------------------------------- Overview -----------------------------------
#> 
#>  General information:
#>  ------------------------
#>  Estimation status                  = Ok
#>  Number of observations             = 75
#>  Weight estimator                   = PLS-PM (OrdPLS)
#>  Inner weighting scheme             = "path"
#>  Type of indicator correlation      = polyserial, Pearson, polychoric
#>  Path model estimator               = OLS
#>  Second-order approach              = NA
#>  Type of path model                 = Linear
#>  Disattenuated                      = Yes (PLSc)
#> 
#>  Construct details:
#>  ------------------
#>  Name   Modeled as     Order         Mode      
#> 
#>  ind60  Common factor  First order   "modeA"   
#>  dem60  Common factor  First order   "modeA"   
#>  dem65  Common factor  First order   "modeA"   
#> 
#> ----------------------------------- Estimates ----------------------------------
#> 
#> Estimated path coefficients:
#> ============================
#>   Path             Estimate  Std. error   t-stat.   p-value
#>   dem60 ~ ind60      0.4278          NA        NA        NA
#>   dem65 ~ ind60      0.1647          NA        NA        NA
#>   dem65 ~ dem60      0.9083          NA        NA        NA
#> 
#> Estimated loadings:
#> ===================
#>   Loading        Estimate  Std. error   t-stat.   p-value
#>   ind60 =~ x1      0.9783          NA        NA        NA
#>   ind60 =~ x2      0.9782          NA        NA        NA
#>   ind60 =~ x3      0.8205          NA        NA        NA
#>   dem60 =~ y1      0.8799          NA        NA        NA
#>   dem60 =~ y2      0.7287          NA        NA        NA
#>   dem60 =~ y3      0.6946          NA        NA        NA
#>   dem60 =~ y4      0.8982          NA        NA        NA
#>   dem65 =~ y5      0.8343          NA        NA        NA
#>   dem65 =~ y6      0.7728          NA        NA        NA
#>   dem65 =~ y7      0.8164          NA        NA        NA
#>   dem65 =~ y8      0.8197          NA        NA        NA
#> 
#> Estimated weights:
#> ==================
#>   Weight         Estimate  Std. error   t-stat.   p-value
#>   ind60 <~ x1      0.3699          NA        NA        NA
#>   ind60 <~ x2      0.3698          NA        NA        NA
#>   ind60 <~ x3      0.3102          NA        NA        NA
#>   dem60 <~ y1      0.3200          NA        NA        NA
#>   dem60 <~ y2      0.2650          NA        NA        NA
#>   dem60 <~ y3      0.2526          NA        NA        NA
#>   dem60 <~ y4      0.3267          NA        NA        NA
#>   dem65 <~ y5      0.2983          NA        NA        NA
#>   dem65 <~ y6      0.2763          NA        NA        NA
#>   dem65 <~ y7      0.2919          NA        NA        NA
#>   dem65 <~ y8      0.2931          NA        NA        NA
#> 
#> ------------------------------------ Effects -----------------------------------
#> 
#> Estimated total effects:
#> ========================
#>   Total effect     Estimate  Std. error   t-stat.   p-value
#>   dem60 ~ ind60      0.4278          NA        NA        NA
#>   dem65 ~ ind60      0.5533          NA        NA        NA
#>   dem65 ~ dem60      0.9083          NA        NA        NA
#> 
#> Estimated indirect effects:
#> ===========================
#>   Indirect effect    Estimate  Std. error   t-stat.   p-value
#>   dem65 ~ ind60        0.3885          NA        NA        NA
#> ________________________________________________________________________________

index <- sample.int(dim(PoliticalDemocracy)[1], 10, replace = FALSE)
dat_test <- PoliticalDemocracy[index, ]

test <- cSEM::predict(
  .object = fit,
  .r= 5,
  .handle_inadmissibles = "ignore",
  .test_data = dat_test,
  .benchmark = "PLS-PM",
  .treat_as_continuous = FALSE
)
test
#> ________________________________________________________________________________
#> ----------------------------------- Overview -----------------------------------
#> 
#>  Number of obs. training            = 75
#>  Number of obs. test                = 10
#>  Number of cv folds                 = NA
#>  Number of repetitions              = 1
#>  Handle inadmissibles               = ignore
#>  Estimator target                   = 'OrdPLS'
#>  Estimator benchmark                = 'OrdPLS'
#>  Disattenuation target              = 'TRUE'
#>  Disattenuation benchmark           = 'TRUE'
#>  Approach to predict                = 'earliest'
#> 
#> ------------------------------ Prediction metrics ------------------------------
#> 
#> 
#>   Name   MAE target  MAE benchmark  RMSE target RMSE benchmark   Q2_predict
#>   y1         4.8000         4.8000       5.6036         5.6036       0.5965
#>   y2         2.6222         2.6210       3.0004         2.9990       0.1178
#>   y3         2.7749         2.7764       3.1312         3.1326       0.4083
#>   y4         2.4177         2.4179       2.9327         2.9332       0.4075
#>   y5         1.6566         1.6567       1.9982         1.9968       0.4488
#>   y6         2.5778         2.5763       3.0645         3.0629       0.1180
#>   y7         2.3878         2.3855       2.6524         2.6500       0.2952
#>   y8         2.7421         2.7416       3.1563         3.1562       0.2920
#> ________________________________________________________________________________
```

<sup>Created on 2023-07-30 with [reprex v2.0.2](https://reprex.tidyverse.org)</sup>

**Comment by huizhao0804z** [comment]
Thanks for all your support!
Do you think there is any way I can realize the replication manually? I'm thinking using another bootstrap

**Comment by FloSchuberth** [comment]
@T-Schamberger : Could you please have a look at this issue. I am the next three weeks on holidays.

My suspicion is that the repetition argument is ignored because a test dataset is provided. In this case, no cross-validation is performed...

**Comment by T-Schamberger** [comment]
@huizhao0804z: As Florian has already mentioned, the repetition argument is ignored if you specify a test data set. If a test data set is provided, the predict() function simply calculates the predictions for all observations in the test data set. In this case, no replication is required. Repetition, i.e. .r different from 1, is only performed in the predict() function if the cross-validation approach of Shmueli et al. (2019) is performed. However, this is not based on a test dataset.
If you want to bootstrap the results for your test data set, unfortunately you need to do this outside the predict function (e.g. using the boot() function from the boot package).

**Comment by huizhao0804z** [comment]
I see. I have another follow-up question. When I used cross-validation, I met an Error: The test dataset contains more categories than the train dataset. I found this is about the thresholds, and is there any way I can fix it?

Thanks for all the support!

Best
________________________________

**Comment by T-Schamberger** [comment]
@huizhao0804z The error message occurs when the data set is split in such a way that not all categories of the sample occur in the training data set. Consequently, there are more/different categories in the test dataset than in the training dataset. As a result, there are categories in the test dataset for which no threshold estimates are available in the training dataset. However, these threshold estimates are required to run OrdPLSpredict. For more details on OrdPLSpredict, see: 
Schamberger, T., Cantaluppi, G., Schuberth, F. (forthcoming). Revisiting and Extending PLS for Ordinal Measurement and Prediction In H. Latan, J. F. Hair, & R. Noonan (Eds.), Partial least squares path modeling: Basic concepts, methodological issues, and applications (2nd ed.). Cham, Switzerland: Springer.

A preprint of the article can be found in chapter 4 of my thesis:
Schamberger, T. (2022) Methodological Advances in Composite-based Structural Equation Modeling. University of Würzburg/ University of Twente, https://doi.org/10.3990/1.9789036553759

Unfortunately, since you have a variable with a large number of categories and at the same time a small sample size, it is very likely that the sample will be split in such a way that there are more categories in the test data set than in the training data set. 

Unfortunately, there is currently no way to apply OrdPLSpredict with cross-validation in these cases.

**Comment by emstruong** [comment]
> A preprint of the article can be found in chapter 4 of my thesis: Schamberger, T. (2022) Methodological Advances in Composite-based Structural Equation Modeling. University of Würzburg/ University of Twente, https://doi.org/10.3990/1.9789036553759

Off-topic, but is this made from R-Markdown/Latex? If so, what's the template?

**Comment by T-Schamberger** [comment]
@emstruong : You can combine Latex and R using knitr.

**Comment by emstruong** [comment]
@T-Schamberger I see, but did you use a particular template to make it look the way it did? My Latex documents certainly don't look like that...

**Comment by FloSchuberth** [comment]
@T-Schamberger : Perhaps you can share the latex file with @emstruong...

**Comment by T-Schamberger** [comment]
@emstruong Sorry for my late reply. Unfortunately, for the book chapter mentioned above, we only snipped the respective code out of a Markdown file to facilitate the submission process. Unfortunately, I don't have a template for an article.

**Comment by emstruong** [comment]
@T-Schamberger No worries! Thanks anyways
