### ISSUE TITLE
Update cSEM.Rmd Vignette

### ISSUE THREAD

**Issue by emstruong** [FloSchuberth/cSEM#520]
Some of the example code involving the `threecommonfactors` dataset list the indicators as `item`s instead of the actual indicator's names.

Compare [this](https://github.com/FloSchuberth/cSEM/blob/35217d4460a94ae88be22c65c2c580ffbe5f42f1/vignettes/cSEM.Rmd#L703)  and [this](https://github.com/FloSchuberth/cSEM/blob/35217d4460a94ae88be22c65c2c580ffbe5f42f1/vignettes/cSEM.Rmd#L429C2-L429C2)

**Comment by FloSchuberth** [comment]
@emstruong Thank you. I have fixed it, see the master branch. This was relict from the past where the indicators were named item1 to item9.
