### ISSUE TITLE
Multigroup Mediation: CIs for group differences in indirect effects

### ISSUE THREAD

**Issue by Necronomnomnom** [FloSchuberth/cSEM#531]
Hello,
first, thank you for cSEM, it is a really cool package! 
I'm calculating a model with three groups and one mediator. I would like to test whether there is a significant difference in the mediation between the groups. My idea to do this was to build upon the explanation of how to calculate the indirect effects for multiple mediators (i.e. https://florianschuberth.com/wp-content/uploads/TutorialsR/Mediation.R). So as a first step I tried to replicate the functions for 3 groups and check whether I get the same results as in the summarize() function and then in a next step I had planned to write functions to calculate the difference between the indirect effects. However, I'm already stuck in the first step, I just don't get CIs with infer() for my self-generated functions. First, I tried the infer()-function without the .quantity = 'CI_percentile' and I got an error message "Fehler in x$Resampled[, i] : Indizierung außerhalb der Grenzen" (error: indexing is not within the borders). Then I added the .quantity argument and I don't get an error, I do get CIs but not for my self-defined functions. 

My code (my groups are named 1,2,3):
Model:
model = "
P ~ E + I
I ~ E

E =~ e1 + e2 + e3 + e4 + e5 + e6
P =~ p1 + p2 + p3 + p4 + p5 + p6
I <~ i1 + i2 + i3 + i4 + i5 
"
Indirekt1 = function(.object) {
  .object$"1"$Estimates$Path_estimates['I','E']*.object$"1"$Estimates$Path_estimates['P','I']
}
Indirekt2 = function(.object) {
  .object$"2"$Estimates$Path_estimates['I','E']*.object$"2"$Estimates$Path_estimates['P','I']
}
Indirekt3 = function(.object) {
  .object$"3"$Estimates$Path_estimates['I','E']*.object$"3"$Estimates$Path_estimates['P','I']
}

testindirekt = csem(data, model, .id = 'groupid', .resample_method = 'bootstrap', .iter_max = 300, .tolerance = 1e-07, .starting_values = liststartvalues, .user_funs = list('IE1'=Indirekt1,'IE2'=Indirekt2,'IE3'=Indirekt3))

outputindirekt = infer(.object= testindirekt, .quantity = 'CI_percentile')

**Comment by FloSchuberth** [comment]
Hey hey,

Thanks for your nice words!

Could you send me (a subset of) your data to replicate the analysis to ***@***.***
Then I will have a look at it tomorrow.

Best regards
Florian
________________________________
Von: Necronomnomnom ***@***.***>
Gesendet: Sonntag, 5. Mai 2024 09:35
An: FloSchuberth/cSEM ***@***.***>
Cc: Subscribed ***@***.***>
Betreff: [FloSchuberth/cSEM] Multigroup Mediation: CIs for group differences in indirect effects (Issue #531)


Hello,
first, thank you for cSEM, it is a really cool package!
I'm calculating a model with three groups and one mediator. I would like to test whether there is a significant difference in the mediation between the groups. My idea to do this was to build upon the explanation of how to calculate the indirect effects for multiple mediators (i.e. https://florianschuberth.com/wp-content/uploads/TutorialsR/Mediation.R). So as a first step I tried to replicate the functions for 3 groups and check whether I get the same results as in the summarize() function and then in a next step I had planned to write functions to calculate the difference between the indirect effects. However, I'm already stuck in the first step, I just don't get CIs with infer() for my self-generated functions. First, I tried the infer()-function without the .quantity = 'CI_percentile' and I got an error message "Fehler in x$Resampled[, i] : Indizierung außerhalb der Grenzen" (error: indexing is not within the borders). Then I added the .quantity argument and I don't get an error, I do get CIs but not for my self-defined functions.

My code (my groups are named 1,2,3):
Model:
model = "
P ~ E + I
I ~ E

E =~ e1 + e2 + e3 + e4 + e5 + e6
P =~ p1 + p2 + p3 + p4 + p5 + p6
I <~ i1 + i2 + i3 + i4 + i5
"
Indirekt1 = function(.object) {
.object$"1"$Estimates$Path_estimates['I','E'].object$"1"$Estimates$Path_estimates['P','I']
}
Indirekt2 = function(.object) {
.object$"2"$Estimates$Path_estimates['I','E'].object$"2"$Estimates$Path_estimates['P','I']
}
Indirekt3 = function(.object) {
.object$"3"$Estimates$Path_estimates['I','E']*.object$"3"$Estimates$Path_estimates['P','I']
}

testindirekt = csem(data, model, .id = 'groupid', .resample_method = 'bootstrap', .iter_max = 300, .tolerance = 1e-07, .starting_values = liststartvalues, .user_funs = list('IE1'=Indirekt1,'IE2'=Indirekt2,'IE3'=Indirekt3))

outputindirekt = infer(.object= testindirekt, .quantity = 'CI_percentile')

**Comment by Necronomnomnom** [comment]
Hello,

thank you for your quick response! I have attached two files - one with my experimental code and one with some simulated data. Thank you in advance for your help!

Best regards

Christin
________________________________
Von: FloSchuberth ***@***.***>
Gesendet: Sonntag, 5. Mai 2024 13:24
An: FloSchuberth/cSEM ***@***.***>
Cc: Necronomnomnom ***@***.***>; Author ***@***.***>
Betreff: Re: [FloSchuberth/cSEM] Multigroup Mediation: CIs for group differences in indirect effects (Issue #531)


Hey hey,

Thanks for your nice words!

Could you send me (a subset of) your data to replicate the analysis to ***@***.***
Then I will have a look at it tomorrow.

Best regards
Florian
________________________________
Von: Necronomnomnom ***@***.***>
Gesendet: Sonntag, 5. Mai 2024 09:35
An: FloSchuberth/cSEM ***@***.***>
Cc: Subscribed ***@***.***>
Betreff: [FloSchuberth/cSEM] Multigroup Mediation: CIs for group differences in indirect effects (Issue #531)


Hello,
first, thank you for cSEM, it is a really cool package!
I'm calculating a model with three groups and one mediator. I would like to test whether there is a significant difference in the mediation between the groups. My idea to do this was to build upon the explanation of how to calculate the indirect effects for multiple mediators (i.e. https://florianschuberth.com/wp-content/uploads/TutorialsR/Mediation.R). So as a first step I tried to replicate the functions for 3 groups and check whether I get the same results as in the summarize() function and then in a next step I had planned to write functions to calculate the difference between the indirect effects. However, I'm already stuck in the first step, I just don't get CIs with infer() for my self-generated functions. First, I tried the infer()-function without the .quantity = 'CI_percentile' and I got an error message "Fehler in x$Resampled[, i] : Indizierung außerhalb der Grenzen" (error: indexing is not within the borders). Then I added the .quantity argument and I don't get an error, I do get CIs but not for my self-defined functions.

My code (my groups are named 1,2,3):
Model:
model = "
P ~ E + I
I ~ E

E =~ e1 + e2 + e3 + e4 + e5 + e6
P =~ p1 + p2 + p3 + p4 + p5 + p6
I <~ i1 + i2 + i3 + i4 + i5
"
Indirekt1 = function(.object) {
.object$"1"$Estimates$Path_estimates['I','E'].object$"1"$Estimates$Path_estimates['P','I']
}
Indirekt2 = function(.object) {
.object$"2"$Estimates$Path_estimates['I','E'].object$"2"$Estimates$Path_estimates['P','I']
}
Indirekt3 = function(.object) {
.object$"3"$Estimates$Path_estimates['I','E']*.object$"3"$Estimates$Path_estimates['P','I']
}

testindirekt = csem(data, model, .id = 'groupid', .resample_method = 'bootstrap', .iter_max = 300, .tolerance = 1e-07, .starting_values = liststartvalues, .user_funs = list('IE1'=Indirekt1,'IE2'=Indirekt2,'IE3'=Indirekt3))

outputindirekt = infer(.object= testindirekt, .quantity = 'CI_percentile')

**Comment by FloSchuberth** [comment]
Hey Christin, 

I cannot see the files :/ Perhaps you can just send them again to f.schuberth(at)utwente.nl

Thank you!

**Comment by Necronomnomnom** [comment]
Okay, I've sent them again

**Comment by FloSchuberth** [comment]
Problem solved via email.
