### ISSUE TITLE
Extend testthat

### ISSUE THREAD

**Issue by FloSchuberth** [FloSchuberth/cSEM#535]
Add additional test for testthat
-[] normal mixture of composite and composites.
-[] empirical example (not population data
-[] cover different types of second-order constructs

**Comment by emstruong** [comment]
Merge with https://github.com/FloSchuberth/cSEM/issues/524 ?

**Comment by FloSchuberth** [comment]
Good idea, please merge, the two.

**Comment by emstruong** [comment]
Merged with https://github.com/FloSchuberth/cSEM/issues/524
