### ISSUE TITLE
Error when trying to execute assess() in a multigroup analysis

### ISSUE THREAD

**Issue by 5mechang** [FloSchuberth/cSEM#539]
I'm trying to do a multigroup analysis with the code below.
The data file contains the answers of a survey and the respondents' attributes (e.g. age, education, etc.) and now I specify the country of residence ("cntr") as a group.
```
model <- "
# measurement model
BI =~ bi_1 + bi_2 + bi_3
PE =~ pe_1 + pe_2
EE =~ ee_1 + ee_2 + ee_3
ATT =~ att_1 + att_2
SI =~ si_1 + si_2
FC =~ fc_1 + fc_2 + fc_3
ENV =~ env_1 + env_2 + env_3 + env_4

# structural model
BI ~ PE + EE + ATT + SI + FC + ENV
"

sem_mga <- csem(
  .data = data,
  .model = model,
  .PLS_weight_scheme_inner = "factorial",
  .disattenuate = F,
  .tolerance = 1e-07,
  .iter_max = 100,
  .resample_method = "bootstrap",
  .R = 500,
  .seed = 123,
  .id = "cntr")

summarize(sem_mga, .ci = "CI_percentile", .alpha = 0.05)
assess(sem_mga)
```
and for `assess(sem_mga)`, I got the output below, while the summary has been displayed successfully.
The output was the same when I only set `.data`, `.model` and `.id`.
```
> assess(EV_sem_mga)
Error in `[.data.frame`(.data, , .id) : undefined columns selected
```
Btw, I got the same result to check if the output is displayed with the example code by Venturini et al. (2023): https://link.springer.com/chapter/10.1007/978-3-031-37772-3_5

Below is the setting of my PC:
OS: Windows 11
R version: 4.4.0
cSEM version: 0.5.0

I'd like you to give some suggestion or solution to this issue.
Thank you in advance!

**Comment by FloSchuberth** [comment]
@5mechang: Thanks for reporting this issue. I will have a look it next week and come back to you.

**Comment by FloSchuberth** [comment]
@5mechang : I spotted the bug and fixed it. You need to install the most recent version from github master branch: 
devtools::install_github("FloSchuberth/cSEM")
However, the Venturini et al. example is still not running as the correlation matrices for some of the groups are not positive definite, which leads to problems if you want to calculate the inverse of that matrix as done for example in the geodesic distance.

**Comment by 5mechang** [comment]
@FloSchuberth After updating the package, the results have been reported successfully!
I appreciate you for dealing with this issue.
