### ISSUE TITLE
`vcov()` for cSEM models?

### ISSUE THREAD

**Issue by ihrke** [FloSchuberth/cSEM#542]
I am trying to extract the estimated covariance matrix of the parameter estimates from the fitted model in `cSEM`.
In `lavaan`, the `vcov()` method returns this matrix but the function is not implemented for the class `cSEMResults`. I could not find it in the `Estimates` field of the fitted model either.
Is there a way to extract that matrix from the model object?

**Comment by emstruong** [comment]
Hi,

Is `res$Estimates$Proxy_VCV` or `res$Estimates$Construct_VCV` what you're looking for? 

Michael

**Comment by emstruong** [comment]
True, I didn't even know this was a thing--I was under the impression that this isn't something to be computed. I think someone else would be better suited to answer

**Comment by FloSchuberth** [comment]
@ihrke : Hey, there is no function to extract the variance-covariance matrix of the parameters. The main reason for that is that there is no closed-form expression for that and the SEs of the parameters are determined via bootstrap. What you could do is run the model with bootstrap, i.e., .resample_method = 'bootstrap'
The resulting cSEM object contains now the bootstrap results: fit$Estimates$Estimates_resample
Using these estimates, you can estimate the variance-covariance matrix of the parameters estimates. 
In the following a small example for the variance-covariance matrix of the path coefficients:
model <- "
# Structural model
EXPE ~ IMAG
QUAL ~ EXPE
VAL  ~ EXPE + QUAL
SAT  ~ IMAG + EXPE + QUAL + VAL 
LOY  ~ IMAG + SAT

# Composite model
IMAG <~ imag1 + imag2 + imag3
EXPE <~ expe1 + expe2 + expe3 
QUAL <~ qual1 + qual2 + qual3 + qual4 + qual5
VAL  <~ val1  + val2  + val3

# Reflective measurement model
SAT  =~ sat1  + sat2  + sat3  + sat4
LOY  =~ loy1  + loy2  + loy3  + loy4
"


# Estimate using defaults
res <- csem(.data = satisfaction, .model = model,.resample_method = 'bootstrap')
cov(res$Estimates$Estimates_resample$Estimates1$Path_estimates$Resampled)


Does this help?

**Comment by ihrke** [comment]
That's what I was looking for, thanks a lot @FloSchuberth!
