### ISSUE TITLE
Error in predict function

### ISSUE THREAD

**Issue by Jant2024** [FloSchuberth/cSEM#543]
Hello! I am using the predict() function for an ordinal dependent variable with numeric independent variables. My code below:

pred<-predict(.object = PLSPike_reduced_numeric, .treat_as_continuous = FALSE, .benchmark = "PLS-PM", .test_data=pike_clean_reduced_numeric[1:250,])

#produces error
Error in apply(X_test[, cat_indicators], 2, max) : 
  dim(X) must have a positive length

I notice when I change one of the independent variables to character instead of numeric, the code runs fine. It seems that the prediction model requires there to be at least two non-numeric variables. 

Could you please advise  on this? 

Some extra information: the dataset is 21 variables (1 ordinal dependent, and 20 numeric independents) with 3647 observations. The PLS model has only formative indicators.

**Comment by FloSchuberth** [comment]
@Jant2024: Thank you very much for raising this issue! 

To better understand the error, could you please send me (a snippet of) your dataset and your R code to the following email address: f.schuberth@utwente.nl
Then I will investigate what is going wrong. 

Thank you

**Comment by FloSchuberth** [comment]
@Jant2024: Thank you for your email. Indeed there was a bug in the predict function. As your model contains a composite with a single categorical indicator, there was a problem with the following line of code: 
apply(X_test[, cat_indicators], 2, max), 
where cat_indicators contains the names of the categorical indicators of the model. In case of a single categorical indicator, the matrix collapse to a vector and the apply returns an error. I have adjusted this as follows: 
apply(X_test[, cat_indicators,drop=FALSE], 2, max)
the drop=FALSE argument prevents that the matrix collapse to a vector. 

Thank you very much for highlighting the bug! 

You can download cSEM from github and then it works again. Therefore, I will close this issue. 

Best regards,
Florian

**Comment by Jant2024** [comment]
Dear Flo,

Many thanks for fixing the bug in the predict function so swiftly. I have run the code and there are no errors. However, when printing the $Actual values for the predict() results, I noticed that the predictions of the dependent variable, which is ordinal (0, 1, 2), include some predictions of the value 3, which is not a valid ordinal result in that variable.

Coud you confirm that the $Actual values include the original independent variable data, and only  the predicted value of the dependent variable (as this variable does not match the original)?

And if so, why is it producing a non-valid ordinal value?

Many thanks,
Josh Anthony
River Restoration Centre

**Comment by FloSchuberth** [comment]
Dear Josh,

The list of actual values contains the predictions for the observed variables connected to dependent composites in your test dataset.

You are right, the predicted values range for your dependent_variable from 1 to 3, while the values in the test dataset range from 0 to 2. This is because the levels are differently coded: a value of 1 means first category, a value of 2 means second category and so on.

For ordinal variables, the numbering is arbitrary because a '1' does not mean 1. You could also recode the categories as A, B, C. It is just important that A<B<C.

HTH

Best regards,
Flo

**Comment by Jant2024** [comment]
Dear Flo,

Many thanks for your help with this. That makes sense and I can see that the ordinal factors do match.

My other question is regarding the bootstrapping results: some p-values have reported 0.0000          . Is this due to a limit of the number of decimal places allowed, and hence the p-value can be considered extremely small. Or does this indicate an issue with the model?

Kind regards,
Josh

**Comment by FloSchuberth** [comment]
Dear Josh,

Looking at the results from the R code that you sent me, I would say this is okay. The p-values are not equal to 0 but just quite small. For the effect of    latent_var9 on latent_var1 I obtain the following:

  latent_var1 ~ latent_var9       0.4045      0.0667    6.0650    0.0000 [ 0.2661; 0.5342 ]

The p-value is calculated in this case:
> 2*(1-pnorm(6.0650))
[1] 1.319536e-09

Which produces a value close to 0. However, in PLS it is more common to consider the bootstrap CI. As you can see, for this effect, the CI does not cover the 0 and therefore one would call this effect as statistically significant.

Best regards,
Flo

**Comment by Jant2024** [comment]
Dear Flo,

Amazing, that makes perfect sense. Thank you so much for your help.

Kind regards,
Josh
