### ISSUE TITLE
Large files in Git (ca. 500mb)

### ISSUE THREAD

**Issue by jhorzek** [FloSchuberth/cSEM#544]
Thanks for the great package! I just wanted to clone it and realized that the repository is around 500 mb large. It seems that there are a few large files in the .git directory that probably ended up there accidentally. Here are a few of those:
```
958665e30d25   29MiB tests/comparisons/igsca_translation/R_out/first_iteration_update_theta_Gamma_W_V/end_results.rds
5ce61b91e2d7   29MiB tests/comparisons/igsca_translation/R_out/first_iteration_update_theta_Gamma_W_V/end_results.rds
8fac18f78292   29MiB tests/comparisons/igsca_translation/R_out/first_composite_update/end_results.rds
ce4fc21b0265   29MiB tests/comparisons/igsca_translation/R_out/first_composite_update/end_results.rds
d4a45ff53468   29MiB tests/comparisons/igsca_translation/R_out/first_factor_update/flip_signs_ind_domi.rds
487b5836e763   29MiB tests/comparisons/igsca_translation/R_out/first_factor_update/flip_signs_ind_domi.rds
9eec6b0cd354   29MiB tests/comparisons/igsca_translation/R_out/first_factor_update/end_results.rds
2b90899b694f   29MiB tests/comparisons/igsca_translation/R_out/first_factor_update/end_results.rds
76fc4d583e2a   42MiB tests/comparisons/igsca_translation/R_out/flip_signs_ind_domi/end_results.rds
f4463f2b6f63   42MiB tests/comparisons/igsca_translation/R_out/flip_signs_ind_domi/end_results.rds
```

**Comment by FloSchuberth** [comment]
Hey @jhorzek: Thank you and happy to hear that you find the package helpful. 

Yes I know, in the gsca branch are quite big files. We are currently working on a proper GSCA implementation including GSCA_m and IGSCA. To compare our approach with the results of existing implementation, we need these large files. Sorry for that, The files in the master branch should be much smaller.

**Comment by jhorzek** [comment]
Thank you for the fast response and for clarifying, @FloSchuberth! Sorry for the false alarm :)
